package pe.com.jdmm21.checklistdocumental.lib.lib003.mapper;

public class Mapper {
    private Mapper() {

    }

    public static final String DOCUMENT_TYPE_ID = "DOCUMENT_TYPE_ID";
    public static final String PCLD_GET_DATA_BY_ID_OPERATION = "SELECT DOCUMENT_TYPE_ID,DOCUMENT_TYPE_GLOBAL_ID,DOCUMENT_TYPE_NAME,REUSE_IND_TYPE,DOCUMENT_TYPE_DESC,VALUED_DOCUMENT_IND_TYPE,CREATION_USER_ID,CREATION_DATE,USER_AUDIT_ID,AUDIT_DATE FROM T_PCLD_DOCUMENT_TYPE_CATALOG WHERE DOCUMENT_TYPE_ID IN (%s)";

}