INSERT INTO T_PCLD_RULES_VERSION (
RULES_PACKAGE_NAME,
RULE_NAME,
RULE_VERSION_NAME,
CASE_BUS_RULE_SERVICE_NAME,
START_VALIDITY_RULE_DATE,
END_VALIDITY_RULE_DATE,
PROCESS_ID,
CREATION_USER_ID,
CREATION_DATE,
USER_AUDIT_ID,
AUDIT_DATE) VALUES ('rulepackagename',
'rulename',
'ruleversion',
'servicedname',
'2020-03-01',
'2020-03-09','4.3.1.8_PE','admin','2020-03-05','admin','2020-03-05');

INSERT INTO T_PCLD_DOCUMENT_TYPE_CATALOG (DOCUMENT_TYPE_ID,DOCUMENT_TYPE_GLOBAL_ID,DOCUMENT_TYPE_NAME,REUSE_IND_TYPE, DOCUMENT_TYPE_DESC,  VALUED_DOCUMENT_IND_TYPE, CREATION_USER_ID,CREATION_DATE ,USER_AUDIT_ID,AUDIT_DATE ) VALUES('0001','PE-GDOC-0001','DNI','1','Documento de identidad del cliente','0','user1',PARSEDATETIME('08/02/20','dd/MM/yy'),'user1',PARSEDATETIME('08/02/20','dd/MM/yy'));
INSERT INTO T_PCLD_DOCUMENT_TYPE_CATALOG (DOCUMENT_TYPE_ID,DOCUMENT_TYPE_GLOBAL_ID,DOCUMENT_TYPE_NAME,REUSE_IND_TYPE, DOCUMENT_TYPE_DESC,  VALUED_DOCUMENT_IND_TYPE, CREATION_USER_ID,CREATION_DATE ,USER_AUDIT_ID,AUDIT_DATE ) VALUES('0002','PE-GDOC-0002','Poder Legal','0','Documento de acción legal','1','user1',PARSEDATETIME('08/02/20','dd/MM/yy'),'user1',PARSEDATETIME('08/02/20','dd/MM/yy'));
INSERT INTO T_PCLD_DOCUMENT_TYPE_CATALOG (DOCUMENT_TYPE_ID,DOCUMENT_TYPE_GLOBAL_ID,DOCUMENT_TYPE_NAME,REUSE_IND_TYPE, DOCUMENT_TYPE_DESC,  VALUED_DOCUMENT_IND_TYPE, CREATION_USER_ID,CREATION_DATE ,USER_AUDIT_ID,AUDIT_DATE ) VALUES('0004','PE-GDOC-0004','Copia Literal de vivienda','0','Documento de vivienda legalizado','1','user1',PARSEDATETIME('08/02/20','dd/MM/yy'),'user1',PARSEDATETIME('08/02/20','dd/MM/yy'));
INSERT INTO T_PCLD_DOCUMENT_TYPE_CATALOG (DOCUMENT_TYPE_ID,DOCUMENT_TYPE_GLOBAL_ID,DOCUMENT_TYPE_NAME,REUSE_IND_TYPE, DOCUMENT_TYPE_DESC,  VALUED_DOCUMENT_IND_TYPE, CREATION_USER_ID,CREATION_DATE ,USER_AUDIT_ID,AUDIT_DATE ) VALUES('0005','PE-GDOC-0005','Recibo de Agua','0','recibo de servicio publico - agua','0','user1',PARSEDATETIME('08/02/20','dd/MM/yy'),'user1',PARSEDATETIME('08/02/20','dd/MM/yy'));
INSERT INTO T_PCLD_DOCUMENT_TYPE_CATALOG (DOCUMENT_TYPE_ID,DOCUMENT_TYPE_GLOBAL_ID,DOCUMENT_TYPE_NAME,REUSE_IND_TYPE, DOCUMENT_TYPE_DESC,  VALUED_DOCUMENT_IND_TYPE, CREATION_USER_ID,CREATION_DATE ,USER_AUDIT_ID,AUDIT_DATE ) VALUES('0009','PE-GDOC-0009','Avatar','1','Imagen de perfil de usuario','0','user1',PARSEDATETIME('08/02/20','dd/MM/yy'),'user1',PARSEDATETIME('08/02/20','dd/MM/yy'));
INSERT INTO T_PCLD_DOCUMENT_TYPE_CATALOG (DOCUMENT_TYPE_ID,DOCUMENT_TYPE_GLOBAL_ID,DOCUMENT_TYPE_NAME,REUSE_IND_TYPE, DOCUMENT_TYPE_DESC,  VALUED_DOCUMENT_IND_TYPE, CREATION_USER_ID,CREATION_DATE ,USER_AUDIT_ID,AUDIT_DATE ) VALUES('0010','PE-GDOC-0010','HRI','1','Documento HRI','1','user1',PARSEDATETIME('08/02/20','dd/MM/yy'),'user1',PARSEDATETIME('08/02/20','dd/MM/yy'));
INSERT INTO T_PCLD_DOCUMENT_TYPE_CATALOG (DOCUMENT_TYPE_ID,DOCUMENT_TYPE_GLOBAL_ID,DOCUMENT_TYPE_NAME,REUSE_IND_TYPE, DOCUMENT_TYPE_DESC,  VALUED_DOCUMENT_IND_TYPE, CREATION_USER_ID,CREATION_DATE ,USER_AUDIT_ID,AUDIT_DATE ) VALUES('0013','PE-GDOC-0013','Deuda otro banco','0','Deuda otro banco','0','user1',PARSEDATETIME('08/02/20','dd/MM/yy'),'user1',PARSEDATETIME('08/02/20','dd/MM/yy'));
INSERT INTO T_PCLD_DOCUMENT_TYPE_CATALOG (DOCUMENT_TYPE_ID,DOCUMENT_TYPE_GLOBAL_ID,DOCUMENT_TYPE_NAME,REUSE_IND_TYPE, DOCUMENT_TYPE_DESC,  VALUED_DOCUMENT_IND_TYPE, CREATION_USER_ID,CREATION_DATE ,USER_AUDIT_ID,AUDIT_DATE ) VALUES('0021','PE-GDOC-0021','Scoring','1','Scoring','0','user1',PARSEDATETIME('08/02/20','dd/MM/yy'),'user1',PARSEDATETIME('08/02/20','dd/MM/yy'));
INSERT INTO T_PCLD_DOCUMENT_TYPE_CATALOG (DOCUMENT_TYPE_ID,DOCUMENT_TYPE_GLOBAL_ID,DOCUMENT_TYPE_NAME,REUSE_IND_TYPE, DOCUMENT_TYPE_DESC,  VALUED_DOCUMENT_IND_TYPE, CREATION_USER_ID,CREATION_DATE ,USER_AUDIT_ID,AUDIT_DATE ) VALUES('0107','PE-GDOC-0107','Voucher de alta de cuenta','1','Voucher','0','user1',PARSEDATETIME('08/02/20','dd/MM/yy'),'user1',PARSEDATETIME('08/02/20','dd/MM/yy'));
INSERT INTO T_PCLD_DOCUMENT_TYPE_CATALOG (DOCUMENT_TYPE_ID,DOCUMENT_TYPE_GLOBAL_ID,DOCUMENT_TYPE_NAME,REUSE_IND_TYPE, DOCUMENT_TYPE_DESC,  VALUED_DOCUMENT_IND_TYPE, CREATION_USER_ID,CREATION_DATE ,USER_AUDIT_ID,AUDIT_DATE ) VALUES('0233','PE-GDOC-0233','VoBo del GOF','1','Vistp bueno del gerente de oficina','0','user1',PARSEDATETIME('08/02/20','dd/MM/yy'),'user1',PARSEDATETIME('08/02/20','dd/MM/yy'));