CREATE TABLE T_PCLD_RULES_VERSION (
    RULES_PACKAGE_NAME VARCHAR(200),
    RULE_NAME VARCHAR(200),
    RULE_VERSION_NAME VARCHAR(200),
    CASE_BUS_RULE_SERVICE_NAME VARCHAR(200),
    START_VALIDITY_RULE_DATE DATE,
    END_VALIDITY_RULE_DATE DATE,
    PROCESS_ID VARCHAR(200),
    CREATION_USER_ID VARCHAR(200),
    CREATION_DATE VARCHAR(200),
    USER_AUDIT_ID VARCHAR(200) ,
    AUDIT_DATE VARCHAR(200) 
);